### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Joker2770** [Augustusmyc/Alpha-Zero-Gomoku#1]
我目前在学习此项目，看老师的代码写得还是比较简洁清爽，我建议考虑支持[gomocup协议](https://plastovicka.github.io/protocl2en.htm)，这样代码里面就不用考虑UI相关，也方便后续更复杂的禁手或者交换规则的修改，我这里用Qt写了一个支持此文本交互协议的跨平台GUI软件[qpiskvork](https://github.com/Joker2770/qpiskvork)可以方便调试。
老师如果有兴趣的话可以参与每年的五子棋AI比赛交流：
[gomocup](https://gomocup.org/)

**Comment by Augustusmyc** [comment]
感谢支持，不过这个项目我近期应该没空维护
